# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('static', 'static'),
        ('routers', 'routers'),
        ('config.py', '.'),
        ('mask_engine.py', '.'),
        ('ner_engine.py', '.'),
        ('stream_buffer.py', '.'),
        ('gateway_core.py', '.'),
        ('database.py', '.'),
        ('load_balancer.py', '.'),
        ('audit.py', '.'),
        ('vault_crypto.py', '.'),
    ],
    hiddenimports=[
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'httpx',
        'fastapi',
        'sse_starlette',
        'sqlite3',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter', 'matplotlib', 'numpy', 'pandas',
        'torch', 'torchvision', 'tensorflow', 'onnxruntime',
        'scipy', 'scikit-learn', 'sklearn', 'skimage', 'pyarrow',
        'moviepy', 'imageio', 'imageio_ffmpeg', 'opencv2', 'cv2',
        'jieba', 'langchain', 'transformers', 'nltk', 'sympy',
        'numba', 'llvmlite', 'yt_dlp', 'PyQt5', 'IPython',
        'zmq', 'orjson', 'gevent', 'grpc', 'lxml',
        'nbformat', 'jsonschema', 'pycparser',
        'wmi', 'pythoncom', 'pywintypes', 'win32com',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='PrivacyGateway',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
