"""
Setup router — first-run configuration wizard endpoint.
Writes .env and persisted secrets so the gateway is ready on next start.
"""
import json
import logging
import secrets
import os
import sys
from pathlib import Path
from typing import Optional

import httpx
from fastapi import APIRouter, Request
from fastapi.responses import JSONResponse

from .dependencies import safe_json, BAD_ENCODING_RESPONSE
from config import _save_persisted_secrets, _load_persisted_secrets

import bcrypt

logger = logging.getLogger(__name__)

router = APIRouter(tags=["setup"])

# Provider display metadata
PROVIDER_URLS: dict[str, str] = {
    "openai": "https://api.openai.com",
    "deepseek": "https://api.deepseek.com",
    "anthropic": "https://api.anthropic.com",
    "google": "https://generativelanguage.googleapis.com",
}

PROVIDER_NAMES: dict[str, str] = {
    "openai": "OpenAI",
    "deepseek": "DeepSeek",
    "anthropic": "Anthropic (Claude)",
    "google": "Google (Gemini)",
    "custom": "Custom / Other",
}


def _get_env_path() -> Path:
    """Resolve .env path using the same logic as config._load_dotenv."""
    if getattr(sys, "frozen", False):
        return Path.cwd() / ".env"
    return Path(__file__).resolve().parent.parent / ".env"


def _read_env() -> dict[str, str]:
    """Read existing .env file key-value pairs."""
    env_path = _get_env_path()
    result: dict[str, str] = {}
    if env_path.exists():
        with env_path.open(encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                key, _, value = line.partition("=")
                key = key.strip()
                value = value.strip()
                if len(value) >= 2 and value[0] == value[-1] and value[0] in ('"', "'"):
                    value = value[1:-1]
                result[key] = value
    return result


def _write_env(env_dict: dict[str, str]) -> None:
    """Atomically write .env file."""
    env_path = _get_env_path()
    env_path.parent.mkdir(parents=True, exist_ok=True)

    # Ordered keys for readability, then alphabetically for the rest
    key_order = [
        "TARGET_LLM",
        "UPSTREAM_API_KEY",
        "LISTEN_PORT",
        "ADMIN_PASSWORD",
        "ADMIN_PASSWORD_HASH",
        "JWT_SECRET",
        "VAULT_ENCRYPT_KEY",
        "MAPPING_TTL",
        "STATELESS_MODE",
        "MASK_ENGINE_TYPE",
        "DB_PATH",
        "DB_TYPE",
    ]
    lines: list[str] = [
        "# AI Privacy Gateway Configuration",
        "# Generated by setup wizard — do not edit by hand",
    ]
    written: set[str] = set()
    for key in key_order:
        if key in env_dict:
            lines.append(f"{key}={env_dict[key]}")
            written.add(key)
    for key, value in env_dict.items():
        if key not in written:
            lines.append(f"{key}={value}")

    content = "\n".join(lines) + "\n"
    tmp = env_path.with_suffix(".env.tmp")
    with tmp.open("w", encoding="utf-8") as f:
        f.write(content)
    tmp.replace(env_path)
    logger.info("Configuration written to %s", env_path)


# ---------------------------------------------------------------------------
#  Validation helpers
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
#  Routes
# ---------------------------------------------------------------------------


@router.post("/api/setup")
async def setup_config(request: Request) -> JSONResponse:
    """
    Save setup configuration and write .env file.

    Accepts JSON body:
      - provider: str  (openai | deepseek | anthropic | google | custom)
      - api_key: str   (required)
      - base_url: str  (required for custom provider)
      - admin_password: str  (optional, min 6 chars)
      - port: int      (optional, 1-65535)
    """
    body, ok = await safe_json(request)
    if not ok:
        return BAD_ENCODING_RESPONSE

    # ---- provider ----
    provider = (body.get("provider") or "").strip().lower()
    if provider not in PROVIDER_URLS and provider != "custom":
        return JSONResponse(
            status_code=400,
            content={
                "error": f"Unsupported provider '{provider}'. "
                f"Must be one of: {', '.join(PROVIDER_URLS.keys())}, custom"
            },
        )

    # ---- api_key ----
    api_key = (body.get("api_key") or "").strip()
    if not api_key:
        return JSONResponse(
            status_code=400, content={"error": "API key is required"}
        )
    if len(api_key) < 8:
        return JSONResponse(
            status_code=400,
            content={"error": "API key appears too short (minimum 8 characters)"},
        )

    # ---- base_url ----
    if provider == "custom":
        base_url = (body.get("base_url") or "").strip().rstrip("/")
        if not base_url:
            return JSONResponse(
                status_code=400,
                content={"error": "API Base URL is required for custom provider"},
            )
        if not (base_url.startswith("http://") or base_url.startswith("https://")):
            return JSONResponse(
                status_code=400,
                content={"error": "Base URL must start with http:// or https://"},
            )
        # Strip trailing /v1 if present — the gateway appends it
        if base_url.endswith("/v1"):
            base_url = base_url[:-3]
    else:
        base_url = PROVIDER_URLS[provider]

    # ---- port ----
    port = body.get("port")
    if port is not None:
        try:
            port_int = int(port)
            if not 1 <= port_int <= 65535:
                raise ValueError
        except (ValueError, TypeError):
            return JSONResponse(
                status_code=400,
                content={"error": "Port must be a number between 1 and 65535"},
            )
    else:
        port_int = None

    # ---- admin_password ----
    admin_password = (body.get("admin_password") or "").strip()
    if admin_password and len(admin_password) < 6:
        return JSONResponse(
            status_code=400,
            content={"error": "Admin password must be at least 6 characters"},
        )

    # ------------------------------------------------------------------
    #  Build env dict — merge with existing .env values (if any)
    # ------------------------------------------------------------------
    env_config = _read_env()

    env_config["TARGET_LLM"] = base_url
    env_config["UPSTREAM_API_KEY"] = api_key
    if port_int:
        env_config["LISTEN_PORT"] = str(port_int)

    # Generate or re-use JWT_SECRET + VAULT_ENCRYPT_KEY
    secrets_dict = _load_persisted_secrets()

    if not env_config.get("JWT_SECRET") and not secrets_dict.get("jwt_secret"):
        jwt_secret = secrets.token_hex(32)
        env_config["JWT_SECRET"] = jwt_secret
        secrets_dict["jwt_secret"] = jwt_secret
    elif secrets_dict.get("jwt_secret"):
        env_config["JWT_SECRET"] = secrets_dict["jwt_secret"]

    if not env_config.get("VAULT_ENCRYPT_KEY") and not secrets_dict.get("vault_encrypt_key"):
        vault_key = secrets.token_hex(32)
        env_config["VAULT_ENCRYPT_KEY"] = vault_key
        secrets_dict["vault_encrypt_key"] = vault_key
    elif secrets_dict.get("vault_encrypt_key"):
        env_config["VAULT_ENCRYPT_KEY"] = secrets_dict["vault_encrypt_key"]

    # Admin password — hash and persist
    if admin_password:
        salt = bcrypt.gensalt()
        pw_hash = bcrypt.hashpw(admin_password.encode(), salt).decode()
        env_config["ADMIN_PASSWORD"] = admin_password
        env_config["ADMIN_PASSWORD_HASH"] = pw_hash
        secrets_dict["admin_password_hash"] = pw_hash
        secrets_dict["admin_password"] = admin_password

    # ------------------------------------------------------------------
    #  Persist to disk
    # ------------------------------------------------------------------
    _write_env(env_config)
    _save_persisted_secrets(secrets_dict)

    # Also update the running config object so the current process
    # picks up the new values immediately.
    try:
        from config import config as app_config

        app_config.TARGET_LLM = base_url
        app_config.UPSTREAM_API_KEY = api_key
        os.environ["TARGET_LLM"] = base_url
        os.environ["UPSTREAM_API_KEY"] = api_key
        if port_int:
            app_config.LISTEN_PORT = port_int
            os.environ["LISTEN_PORT"] = str(port_int)
        if admin_password:
            app_config.ADMIN_PASSWORD = admin_password
            app_config.ADMIN_PASSWORD_HASH = pw_hash
            os.environ["ADMIN_PASSWORD"] = admin_password
            os.environ["ADMIN_PASSWORD_HASH"] = pw_hash
    except Exception:
        logger.warning("Could not update runtime config; restart recommended")

    final_port = port_int or int(env_config.get("LISTEN_PORT", "9999"))

    return JSONResponse({
        "success": True,
        "message": "Configuration saved successfully",
        "gateway_url": f"http://localhost:{final_port}/v1/chat/completions",
        "admin_url": f"http://localhost:{final_port}/admin",
        "port": final_port,
        "provider": provider,
        "endpoint": base_url,
    })


@router.get("/api/setup/status")
async def setup_status() -> JSONResponse:
    """Check whether the gateway has been configured (.env exists with content)."""
    env_path = _get_env_path()
    configured = env_path.exists() and env_path.stat().st_size > 0
    return JSONResponse({"configured": configured})


@router.post("/api/setup/test-connection")
async def test_connection(request: Request) -> JSONResponse:
    """
    Test an API key against a provider endpoint (server-side, no CORS).
    Accepts JSON body:
      - provider: str
      - api_key: str
      - base_url: str  (required for custom provider)
    """
    body, ok = await safe_json(request)
    if not ok:
        return BAD_ENCODING_RESPONSE

    provider = (body.get("provider") or "").strip().lower()
    api_key_value = (body.get("api_key") or "").strip()

    if not api_key_value:
        return JSONResponse(
            status_code=400,
            content={"success": False, "error": "API key is required"},
        )

    if provider == "custom":
        base_url = (body.get("base_url") or "").strip().rstrip("/")
        if not base_url:
            return JSONResponse(
                status_code=400,
                content={"success": False, "error": "Base URL is required for custom provider"},
            )
    elif provider in PROVIDER_URLS:
        base_url = PROVIDER_URLS[provider]
    else:
        return JSONResponse(
            status_code=400,
            content={"success": False, "error": f"Unknown provider: {provider}"},
        )

    # Strip /v1 suffix if present
    if base_url.endswith("/v1"):
        base_url = base_url[:-3]

    test_url = f"{base_url.rstrip('/')}/v1/models"

    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            resp = await client.get(
                test_url,
                headers={"Authorization": f"Bearer {api_key_value}"},
            )

        if resp.status_code == 200:
            return JSONResponse({
                "success": True,
                "message": "Connection successful — API key is valid",
            })
        elif resp.status_code == 401:
            return JSONResponse({
                "success": False,
                "error": "Unauthorized — API key is invalid or expired",
                "status_code": 401,
            })
        else:
            return JSONResponse({
                "success": False,
                "error": f"Server returned HTTP {resp.status_code}",
                "status_code": resp.status_code,
            })
    except httpx.TimeoutException:
        return JSONResponse({
            "success": False,
            "error": "Connection timed out — check the endpoint URL",
        })
    except httpx.ConnectError:
        return JSONResponse({
            "success": False,
            "error": "Could not connect — check the endpoint URL",
        })
    except Exception as exc:
        logger.warning("Test connection error: %s", exc)
        return JSONResponse({
            "success": False,
            "error": f"Connection failed: {exc}",
        })
